[package]
name = "heaparray"
version = "0.4.3"
authors = ["Albert Liu <albertymliu@gmail.com>"]
edition = "2018"
repository = "https://github.com/A1Liu/heaparray-rs"
description = "Flexible support for dynamically-sized types, using heap-allocated array of structs"
readme = "README.md"
keywords = ["array", "heap", "dynamically-sized-types"]
categories = ["data-structures", "memory-management"]
license = "MIT"

[dependencies]
containers-rs = "^0.5.0"
const-utils = "0.1.1"

[dev-dependencies]
interloc = "0.1.0"

[features]
default = []
no-asserts = ["mem-block-fast-alloc","mem-block-no-check"] # does what it says on the tin - removes all assertions; this can cause undefined behavior.
mem-block-fast-alloc = []
mem-block-no-check = []
