[package]
name = "heaparray"
version = "0.1.5"
authors = ["Albert Liu <albertymliu@gmail.com>"]
edition = "2018"
repository = "https://github.com/A1Liu/heaparray-rs"
description = "Heap-allocated array with optional metadata field"
readme = "README.md"
license = "MIT"

[dependencies]
containers-rs = "= 0.1.4"
